# Generated by Django 5.0.2 on 2024-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GazolePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('station_id', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('essance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
